runtime: python311

env_variables:
  MISTRAL_API_KEY: your_mistral_api_key_here
  GLM_API_KEY: your_glm_api_key_here
  OLLAMA_API_KEY: your_ollama_api_key_here

automatic_scaling:
  min_instances: 1
  max_instances: 10